[package]
name = "secrets"
version = "1.2.0"
edition = "2024"

rust-version = "1.85.0"

authors = ["Stephen Touset <stephen@touset.org>"]
description = "Protected-access memory for cryptographic secrets"

license = "MIT OR Apache-2.0"
homepage = "https://github.com/stouset/secrets"
repository = "https://github.com/stouset/secrets"
documentation = "https://stouset.github.io/secrets"
readme = "README.md"

keywords = ["crypto", "cryptography", "allocator"]

[dependencies]
libc = '0.2'
libsodium-sys-stable = { git = "https://github.com/jedisct1/libsodium-sys-stable", tag = "1.22.4" }

[features]
allow-coredumps = []
# Enable this feature if you want to use the latest stable version of libsodium
fetch-latest = ["libsodium-sys-stable/fetch-latest"]
# Enable optimized build for the current platform
optimized = ["libsodium-sys-stable/optimized"]
# Do not build deprecated APIs
minimal = ["libsodium-sys-stable/minimal"]
